### ISSUE TITLE
SVG on Android

### ISSUE THREAD

**Issue by DrMartinLutherXing** [DrMartinLutherXing/mobile-game-controller#9]
SVG does not appear to work on android.
Tried exporting to PNG, but got a server error: err_content_length_mismatch for large MB size images.

Should get high quality jpeg or png.

try png same size as svg but lower quality.

**Comment by bubbleboy14** [comment]
closing for now, as this works in latest android. still doesn't work in old versions, but probably tough tomatoes, for now at least.
